CREATE DATABASE InventoryDb;
GO

USE InventoryDb;
GO

CREATE TABLE Categories
(
    Id UNIQUEIDENTIFIER NOT NULL,
    Name NVARCHAR(100) NOT NULL,
    Status BIT NOT NULL
);

CREATE TABLE Products
(
    Id UNIQUEIDENTIFIER NOT NULL,
    Name NVARCHAR(100) NOT NULL,
    Stock INT NOT NULL,
    Status BIT NOT NULL,
    CategoryId UNIQUEIDENTIFIER NOT NULL
);

CREATE TABLE InventoryMovements
(
    Id UNIQUEIDENTIFIER NOT NULL,
    ProductId UNIQUEIDENTIFIER NOT NULL,
    Quantity INT NOT NULL,
    CreatedAt DATETIME2 NOT NULL
);